project:
  type: website

website:
  title: "Research Engineering Group"
  site-url: "https://alan-turing-institute.github.io/REG/"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



