on:
  workflow_dispatch:
  push:
    branches:
      - svelte

name: Publish Svelte

jobs:
  publish-svelte:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build --base /REG/svelte

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          destination_dir: svelte
          publish_branch: gh-pages
